version: '3'

services:
  rabbitmq:
    image: 'rabbitmq:latest'
    ports:
      - '5672'
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"